"""Short demonstration cues checked against the library descriptions in SeedData.swift.

These explain the loop; they do not replace the exercise timer or the written instructions.
Transitions can override the destination pose's hold cue.
"""
MOVEMENT_CUES = {
    'Quad Sets': {'rest': 'Relax your thigh', 'rest>press': 'Press your knee down', 'press': 'Tighten thigh · hold 5 sec'},
    'Straight Leg Raises': {'down': 'Lower slowly', 'down>up': 'Raise the straight leg', 'up': 'Stop at bent-knee height'},
    'Short Arc Quads': {'bent': 'Lower slowly', 'bent>straight': 'Straighten over the towel', 'straight': 'Hold straight · 2 sec'},
    'Terminal Knee Extension': {'bent': 'Bend knee slightly', 'bent>straight': 'Press against the band', 'straight': 'Knee straight · foot flat'},
    'Wall Sit': {'top': 'Back against the wall', 'top>bottom': 'Slide down slowly', 'bottom': 'Hold · knees at 90°',
                 'bottom>top': 'Slide up slowly'},
    'Step Ups': {'floor': 'Stand in front of step', 'liftL': 'Step up · left foot first', 'leadUp': 'Plant your left foot',
                 'liftR': 'Bring the right foot up', 'top': 'Stand tall on the step', 'liftDown': 'Step down · left first',
                 'leadDown': 'Control your descent', 'trailDown': 'Bring the right foot down'},
    'Clamshells': {'closed': 'Knees bent · feet together', 'closed>open': 'Open the top knee',
                   'open': 'Feet together · hips stacked', 'open>closed': 'Lower without rolling back'},
    'Glute Bridges': {'down': 'Lower hips slowly', 'down>up': 'Press through your heels', 'up': 'Squeeze glutes at the top'},
    'Side-Lying Hip Abduction': {'down': 'Legs straight · hips stacked', 'down>up': 'Lift the top leg',
                                'up': 'About 45° · toes forward', 'up>down': 'Lower with control'},
    'Donkey Kicks': {'quad': 'Hands and knees · back flat', 'quad>kick': 'Lift foot toward ceiling',
                     'kick': 'Keep knee bent at 90°', 'kick>quad': 'Return with control'},
    'External Rotation with Band': {'in': 'Return slowly · elbow tucked', 'in>out': 'Rotate forearm outward',
                                     'out': 'Elbow stays at your side'},
    'Internal Rotation with Band': {'out': 'Return slowly · elbow tucked', 'out>in': 'Rotate across your body',
                                     'in': 'Elbow stays at your side'},
    'Shoulder Rows': {'reach': 'Return slowly', 'reach>pull': 'Pull toward your mid-torso',
                      'pull': 'Elbows close · squeeze back'},
    'Scapular Retraction': {'rest': 'Release · arms relaxed', 'rest>squeeze': 'Draw shoulder blades back',
                            'squeeze': 'Arms still · hold 5 sec'},
    'Heel Raises': {'flat': 'Lower heels slowly', 'flat>up': 'Rise onto your toes', 'up': 'Hold briefly at the top'},
    'Ankle Eversion with Band': {'sit': 'Return with control', 'sit>evert': 'Turn your foot outward',
                                  'evert': 'Keep knee and shin still'},
    'Towel Scrunches': {'flat': 'Straighten your toes', 'curl': 'Scrunch towel with toes'},
    'Dead Bug': {'start': 'Arms up · knees at 90°', 'a': 'Right arm + left leg', 'b': 'Left arm + right leg',
                 'a>start': 'Return · keep back flat', 'b>start': 'Return · keep back flat'},
    'Bird Dog': {'rest': 'Hands and knees · back flat', 'rest>a': 'Right arm + left leg',
                 'a': 'Hold a straight line · 2 sec', 'a>rest': 'Return with control',
                 'rest>b': 'Left arm + right leg', 'b': 'Hold a straight line · 2 sec', 'b>rest': 'Return with control'},
    'Pelvic Tilts': {'rest': 'Release gently', 'rest>tilt': 'Tighten your abdominals', 'tilt': 'Flatten lower back · hold'},
    'Plank': {'knees': 'Set elbows under shoulders', 'knees>full': 'Lift onto forearms and toes',
               'full': 'Hold straight · breathe', 'full>knees': 'Lower knees with control'},
    'Supine Marching': {'rest': 'Keep your lower back still', 'r': 'Lift right foot a little',
                         'l': 'Lift left foot a little', 'r>rest': 'Lower right foot', 'l>rest': 'Lower left foot'},
    'Hamstring Stretch': {'flat': 'Strap around your foot', 'flat>up': 'Gently raise straight leg',
                           'up': 'Hold a comfortable stretch', 'up>flat': 'Lower gently'},
    'Quad Stretch': {'stand': 'Use the wall for balance', 'stand>stretch': 'Bend knee · grasp ankle',
                      'stretch': 'Stand tall · knees together', 'stretch>stand': 'Release gently'},
    'Hip Flexor Stretch': {'kneel': 'Half-kneel · trunk upright', 'kneel>push': 'Ease your hips forward',
                            'push': 'Hold · keep trunk upright', 'push>kneel': 'Ease back slowly'},
    'Piriformis Stretch': {'cross': 'Right ankle over left knee', 'cross>pull': 'Pull legs toward your chest',
                            'pull': 'Hold the figure-four stretch', 'pull>cross': 'Release gently'},
    'Calf Stretch (Gastrocnemius)': {'upright': 'Back knee straight · heel down', 'upright>lean': 'Lean gently toward wall',
                                      'lean': 'Hold · keep back heel down', 'lean>upright': 'Ease back slowly'},
    'IT Band Stretch': {'upright': 'Right foot behind the left', 'upright>lean': 'Lean left · right hip out',
                         'lean': 'Hold the side stretch', 'lean>upright': 'Return upright'},
    'Thoracic Rotation': {'center': 'Sit tall · arms crossed', 'left': 'Turn left · hold', 'right': 'Turn right · hold',
                           'left>center': 'Return to center', 'right>center': 'Return to center'},
    'Shoulder Cross-Body Stretch': {'rest': 'Relax your arms', 'rest>stretch': 'Bring arm across your chest',
                                    'stretch': 'Support just above elbow', 'stretch>rest': 'Release gently'},
    'Neck Stretch': {'tall': 'Return to center', 'left': 'Left ear toward shoulder', 'right': 'Right ear toward shoulder'},
    'Single Leg Stance': {'stand': 'Stay near support', 'lift': 'Lift one foot slightly', 'a': 'Balance · minimize sway',
                           'b': 'Balance · minimize sway', 'b>lift': 'Keep your balance', 'lift>stand': 'Lower your foot'},
    'Tandem Stance': {'neutral': 'Stand near support', 'aStep': 'Place left foot in front', 'aHalf': 'Bring feet into one line',
                       'aShift': 'Set heel against toe', 'a': 'Left in front · hold', 'bStep': 'Place right foot in front',
                       'bHalf': 'Bring feet into one line', 'bShift': 'Set heel against toe', 'b': 'Right in front · hold',
                       'a>aShift': 'Step back with control', 'aShift>aHalf': 'Step back with control',
                       'aHalf>aStep': 'Return to standing', 'aStep>neutral': 'Return to standing',
                       'b>bShift': 'Step back with control', 'bShift>bHalf': 'Step back with control',
                       'bHalf>bStep': 'Return to standing', 'bStep>neutral': 'Return to standing'},
    'Knee Flexion/Extension': {'sit': 'Sit tall · thigh stays still', 'ext': 'Straighten your knee', 'flex': 'Bend knee comfortably'},
    'Cervical Range of Motion': {'n': 'Return to center', 'up': 'Look up gently', 'down': 'Look down gently',
                                 'tl': 'Turn your head left', 'tr': 'Turn your head right',
                                 'sl': 'Left ear toward shoulder', 'sr': 'Right ear toward shoulder'},
    'Shoulder Pendulum': {'n': 'Support yourself on the table', 'sL': 'Sway · let your arm hang',
                           'sR': 'Sway · let your arm hang', **{f'c{i}': 'Gently circle the loose arm' for i in range(8)}},
    'Lumbar Flexion/Extension': {'stand': 'Return upright', 'fwd': 'Bend forward from the hips', 'back': 'Gently extend backward'},
}
